import { create } from "zustand";
import { persist } from "zustand/middleware";
import { sanitizePlainText } from "../lib/content-validation";
import { seedAccounts, seedClientProfiles, seedOffers, seedProviders, seedRequests, seedReviews, seedReports, seedRoleAssignments, type MessageType, type ProviderOffer, type ProviderProfile, type QuoteRequest, type Report, type Review } from "../lib/mvp-data";
import type { ClientProfile, RoleAssignment, UserAccount } from "../lib/identity";
import { useAuthStore } from "./auth-store";

export type RequestActor={id:string;providerId:string|null};
export type RequestRole="requester"|"provider";
export function getRequestRole(request:QuoteRequest,user:RequestActor):RequestRole|null {if(request.requesterId===user.id)return"requester";if(user.providerId&&request.providerId===user.providerId)return"provider";return null}

interface MvpState {
  accounts:UserAccount[];clientProfiles:ClientProfile[];roleAssignments:RoleAssignment[];
  providers:ProviderProfile[];offers:ProviderOffer[];requests:QuoteRequest[];reviews:Review[];reports:Report[];
  savedProviderIds:string[];toast:string|null;
  setToast:(message:string|null)=>void;updateProvider:(id:string,patch:Partial<ProviderProfile>)=>boolean;addOffer:(offer:ProviderOffer)=>boolean;updateOffer:(id:string,patch:Partial<ProviderOffer>)=>boolean;archiveOffer:(id:string)=>boolean;createRequest:(request:QuoteRequest)=>boolean;addMessage:(id:string,text:string,type?:MessageType,metadata?:Record<string,unknown>)=>boolean;sendQuote:(id:string,price:string,delivery:string)=>boolean;acceptQuote:(id:string)=>boolean;markConversationRead:(id:string)=>void;confirmRequest:(id:string)=>boolean;closeRequest:(id:string)=>boolean;addReview:(review:Review)=>boolean;addReport:(report:Report)=>boolean;updateReport:(id:string,status:Report["status"])=>boolean;toggleSavedProvider:(id:string)=>void;
}

const now=()=>new Date().toISOString();const closedStatuses=["COMPLETED","CLOSED_BY_REQUESTER","CLOSED_BY_PROVIDER","CANCELLED"];
const fail=(set:(value:Partial<MvpState>)=>void,message:string)=>{set({toast:message});return false};
function actor(state:MvpState){const user=useAuthStore.getState().user;if(!user)return null;const account=state.accounts.find(item=>item.id===user.id)??{id:user.id,email:user.email,displayName:user.name??user.email,status:"ACTIVE" as const,emailVerifiedAt:user.emailVerified,phoneVerifiedAt:user.emailVerified,createdAt:user.createdAt,updatedAt:user.createdAt};if(account.status!=="ACTIVE")return null;const provider=state.providers.find(item=>item.id===user.providerProfileId||item.ownerUserId===user.id);const systemRoles=user.roleLabels??[user.role];return{session:{userId:user.id,systemRoles},account,provider,requestActor:{id:account.id,providerId:provider?.id??user.providerProfileId??user.providers[0]?.id??null}}}

export const useMvpStore=create<MvpState>()(persist((set,get)=>({
  accounts:seedAccounts,clientProfiles:seedClientProfiles,roleAssignments:seedRoleAssignments,providers:seedProviders,offers:seedOffers,requests:seedRequests,reviews:seedReviews,reports:seedReports,savedProviderIds:[],toast:null,
  setToast:toast=>set({toast}),
  updateProvider:(id,patch)=>{const identity=actor(get());if(!identity||identity.provider?.id!==id)return fail(set,"No tenés permiso para editar este perfil.");set(state=>({providers:state.providers.map(provider=>provider.id===id?{...provider,...patch,updatedAt:now()}:provider),toast:"Perfil público actualizado."}));return true},
  addOffer:offer=>{const identity=actor(get());if(!identity||offer.providerId!==identity.provider?.id)return fail(set,"No tenés permiso para publicar en este perfil.");set(state=>({offers:[offer,...state.offers],toast:"Producto o servicio agregado al catálogo."}));return true},
  updateOffer:(id,patch)=>{const identity=actor(get());const offer=get().offers.find(item=>item.id===id);if(!identity||!offer||offer.providerId!==identity.provider?.id)return fail(set,"No tenés permiso para editar esta oferta.");set(state=>({offers:state.offers.map(item=>item.id===id?{...item,...patch,updatedAt:now()}:item),toast:"Oferta actualizada."}));return true},
  archiveOffer:id=>{const identity=actor(get());const offer=get().offers.find(item=>item.id===id);if(!identity||!offer||offer.providerId!==identity.provider?.id)return fail(set,"No tenés permiso para eliminar esta oferta.");set(state=>({offers:state.offers.map(item=>item.id===id?{...item,status:"ARCHIVED",updatedAt:now()}:item),toast:"Oferta eliminada del perfil público."}));return true},
  createRequest:request=>{const state=get();const identity=actor(state);if(!identity||request.requesterId!==identity.account.id)return fail(set,"Necesitás una sesión válida para crear la solicitud.");if(request.providerId===identity.provider?.id)return fail(set,"No podés enviarte una solicitud a tu propio perfil.");const tenMinutesAgo=Date.now()-600000;const duplicate=state.requests.some(item=>item.requesterId===identity.account.id&&item.providerId===request.providerId&&item.title.toLowerCase()===request.title.toLowerCase()&&new Date(item.createdAt).getTime()>tenMinutesAgo);if(duplicate)return fail(set,"Ya enviaste una solicitud igual a este proveedor. Esperá unos minutos antes de repetirla.");const profile=identity.provider;const ageDays=profile?Math.floor((Date.now()-new Date(profile.createdAt).getTime())/86400000):999;const limited=!!profile&&profile.verificationLevel!=="COMPLETE"&&ageDays<30;const active=state.requests.filter(item=>item.requesterId===identity.account.id&&!closedStatuses.includes(item.status)).length;if(limited&&active>=3)return fail(set,"Tenés demasiadas solicitudes activas. Cerrá o completá alguna antes de crear otra.");set(current=>({requests:[request,...current.requests],offers:request.productId?current.offers.map(offer=>offer.id===request.productId?{...offer,inquiryCount:offer.inquiryCount+1}:offer):current.offers,toast:"Solicitud creada. La conversación ya está protegida dentro de la app."}));return true},
  addMessage:(id,text,type="TEXT",metadata)=>{const state=get();const identity=actor(state);const request=state.requests.find(item=>item.id===id);if(!identity||!request)return fail(set,"No encontramos una sesión o conversación válida.");const role=getRequestRole(request,identity.requestActor);if(!role)return fail(set,"No participás en esta conversación.");const clean=sanitizePlainText(text);if(!clean)return fail(set,"Escribí un mensaje antes de enviarlo.");set(current=>({requests:current.requests.map(item=>item.id===id?{...item,status:item.status==="OPEN"?"IN_CONVERSATION":item.status,updatedAt:now(),unreadByProvider:role==="requester"?item.unreadByProvider+1:item.unreadByProvider,unreadByRequester:role==="provider"?item.unreadByRequester+1:item.unreadByRequester,messages:[...item.messages,{id:crypto.randomUUID(),author:role,senderId:identity.account.id,type,text:clean,metadata,createdAt:now()}]}:item)}));return true},
  sendQuote:(id,price,delivery)=>{const state=get();const identity=actor(state);const request=state.requests.find(item=>item.id===id);if(!identity||!request||getRequestRole(request,identity.requestActor)!=="provider")return fail(set,"Solo el proveedor de esta solicitud puede enviar una cotización.");set(current=>({requests:current.requests.map(item=>item.id===id?{...item,status:item.status==="OPEN"?"IN_CONVERSATION":item.status,quotedPriceLabel:sanitizePlainText(price),quotedDeliveryTime:sanitizePlainText(delivery),updatedAt:now(),unreadByRequester:item.unreadByRequester+1,messages:[...item.messages,{id:crypto.randomUUID(),author:"provider",senderId:identity.account.id,type:"QUOTE_SUMMARY",text:`📋 Cotización enviada:\n💰 Precio: ${sanitizePlainText(price)}\n📅 Tiempo de entrega: ${sanitizePlainText(delivery)}`,metadata:{price,delivery},createdAt:now()}]}:item),toast:"Cotización enviada dentro de la conversación."}));return true},
  acceptQuote:id=>{const state=get();const identity=actor(state);const request=state.requests.find(item=>item.id===id);if(!identity||!request||getRequestRole(request,identity.requestActor)!=="requester")return fail(set,"Solo quien solicitó el trabajo puede aceptar la cotización.");set(current=>({requests:current.requests.map(item=>item.id===id?{...item,updatedAt:now(),messages:[...item.messages,{id:crypto.randomUUID(),author:"system",senderId:"SYSTEM",type:"STATUS_UPDATE",text:`✅ El cliente aceptó la cotización: ${request.quotedPriceLabel}`,createdAt:now()}]}:item),toast:"Cotización aceptada."}));return true},
  markConversationRead:id=>set(state=>{const identity=actor(state);if(!identity)return{};return{requests:state.requests.map(request=>{if(request.id!==id)return request;const role=getRequestRole(request,identity.requestActor);return role?{...request,[role==="provider"?"unreadByProvider":"unreadByRequester"]:0}:request})}}),
  confirmRequest:id=>{const state=get();const identity=actor(state);const request=state.requests.find(item=>item.id===id);if(!identity||!request)return fail(set,"No encontramos una sesión o solicitud válida.");const role=getRequestRole(request,identity.requestActor);if(!role)return fail(set,"No participás en esta solicitud.");const timestamp=now();if(role==="requester"&&request.confirmedByRequesterAt||role==="provider"&&request.confirmedByProviderAt)return fail(set,"Tu confirmación ya estaba registrada.");set(current=>({requests:current.requests.map(item=>{if(item.id!==id)return item;const next={...item,updatedAt:timestamp,confirmedByRequesterAt:role==="requester"?timestamp:item.confirmedByRequesterAt,confirmedByProviderAt:role==="provider"?timestamp:item.confirmedByProviderAt};if(next.confirmedByRequesterAt&&next.confirmedByProviderAt)return{...next,status:"COMPLETED" as const,completedAt:timestamp,messages:[...next.messages,{id:crypto.randomUUID(),author:"system" as const,senderId:"SYSTEM" as const,type:"REVIEW_UNLOCKED" as const,text:"Solicitud completada. Ya podés dejar una reseña verificada.",createdAt:timestamp}]};return{...next,messages:[...next.messages,{id:crypto.randomUUID(),author:"system" as const,senderId:"SYSTEM" as const,type:"COMPLETION_REQUEST" as const,text:`${role==="provider"?"El proveedor":"El cliente"} confirmó el trabajo. Falta la confirmación de la otra parte.`,createdAt:timestamp}]}}),toast:"Tu confirmación quedó registrada."}));return true},
  closeRequest:id=>{const state=get();const identity=actor(state);const request=state.requests.find(item=>item.id===id);if(!identity||!request)return fail(set,"No encontramos una sesión o solicitud válida.");const role=getRequestRole(request,identity.requestActor);if(!role)return fail(set,"No participás en esta solicitud.");set(current=>({requests:current.requests.map(item=>item.id===id?{...item,status:role==="requester"?"CLOSED_BY_REQUESTER":"CLOSED_BY_PROVIDER",updatedAt:now()}:item),toast:"Tu parte de la solicitud fue cerrada."}));return true},
  addReview:review=>{const state=get();const identity=actor(state);const request=state.requests.find(item=>item.id===review.requestId);if(!identity||!request||request.status!=="COMPLETED"||request.requesterId!==identity.account.id||review.reviewerId!==identity.account.id||state.reviews.some(item=>item.requestId===review.requestId&&item.reviewerId===review.reviewerId))return fail(set,"Esta reseña no está habilitada para tu cuenta.");set(current=>({reviews:[review,...current.reviews],toast:"Reseña publicada."}));return true},
  addReport:report=>{const identity=actor(get());if(!identity||report.reporterId!==identity.account.id)return fail(set,"No podés enviar un reporte a nombre de otra persona.");set(state=>({reports:[report,...state.reports],toast:"Reporte enviado. El equipo lo revisará manualmente."}));return true},
  updateReport:(id,status)=>{const identity=actor(get());const canReview=!!identity&&(identity.session.systemRoles.includes("ADMIN_REVIEWER")||identity.session.systemRoles.includes("SUPER_ADMIN"));if(!canReview)return fail(set,"Solo administración puede revisar reportes.");set(state=>({reports:state.reports.map(report=>report.id===id?{...report,status}:report),toast:"Estado del reporte actualizado."}));return true},
  toggleSavedProvider:id=>{const identity=actor(get());if(!identity)return void set({toast:"Iniciá sesión para guardar proveedores."});set(state=>{const saved=state.savedProviderIds.includes(id);return{savedProviderIds:saved?state.savedProviderIds.filter(item=>item!==id):[...state.savedProviderIds,id],toast:saved?"Proveedor eliminado de guardados.":"Proveedor guardado."}})},
}),{name:"conecta-emprende-domain-v1",partialize:state=>({accounts:state.accounts,clientProfiles:state.clientProfiles,roleAssignments:state.roleAssignments,providers:state.providers,offers:state.offers,requests:state.requests,reviews:state.reviews,reports:state.reports,savedProviderIds:state.savedProviderIds})}));
